version: '3.1'

services:
  db:
    container_name: db
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db/backup:/docker-entrypoint-initdb.d
  tomcat:
    container_name: webapp
    image: tomcat:latest
    ports:
      - 8080:8080
    volumes:
      - ./target:/usr/local/tomcat/webapps

