version: '3.1'

services:
  tomcat:
    container_name: webapp
    image: tomcat:latest
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - shared-network
    volumes:
      - ./target/Spring-1.0.0:/usr/local/tomcat/webapps/ROOT
  db:
    container_name: db
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - ./db:/docker-entrypoint-initdb.d
networks:
  shared-network:

